define({
	player : "/imgs/character.png",
	grass  : "/imgs/grass_1.png",
	wall   : "/imgs/wall_1.png",
    inventory_cell : "/imgs/inventory_cell.png",
    "ammo_slot" :  "/imgs/slots/ammo.png",
    "back_slot" :  "/imgs/slots/back.png",
    "bow_slot" :  "/imgs/slots/bow.png",
    "chest_slot" :  "/imgs/slots/chest.png",
    "feet_slot" :  "/imgs/slots/feet.png",
    "finger_slot" :  "/imgs/slots/finger.png",
    "hands_slot" :  "/imgs/slots/hands.png",
    "head_slot" :  "/imgs/slots/head.png",
    "legs_slot" :  "/imgs/slots/legs.png",
    "neck_slot" :  "/imgs/slots/neck.png",
    "relic_slot" :  "/imgs/slots/relic.png",
    "shield_slot" :  "/imgs/slots/shield.png",
    "shirt_slot" :  "/imgs/slots/shirt.png",
    "shoulder_slot" :  "/imgs/slots/shoulder.png",
    "tabard_slot" :  "/imgs/slots/tabard.png",
    "trinket_slot" :  "/imgs/slots/trinket.png",
    "waist_slot" :  "/imgs/slots/waist.png",
    "weapon_slot" :  "/imgs/slots/weapon.png",
    "wrists_slot" :  "/imgs/slots/wrists.png",
    item : "/imgs/angband/Ring of Tulkas.png",
    "trackbar_background" : "/imgs/trackbar/trackbar_background.png",
    "trackbar_bar" : "/imgs/trackbar/trackbar_bar.png",
    "trackbar_slider" : "/imgs/trackbar/trackbar_slider.png",
    "trackbar_exit" : "/imgs/trackbar/trackbar_exit.png",
    "trackbar_ok" : "/imgs/trackbar/trackbar_ok.png",
    "Food" : "/imgs/Food.png",
	zombie : {
		corpse: "/imgs/zombie/zombie_corpse_1.png",
		legs  : [
			"/imgs/zombie/zombie_legs_1.png",
			"/imgs/zombie/zombie_legs_2.png",
			"/imgs/zombie/zombie_legs_3.png",
			"/imgs/zombie/zombie_legs_4.png",
			"/imgs/zombie/zombie_legs_5.png",
			"/imgs/zombie/zombie_legs_6.png",
			"/imgs/zombie/zombie_legs_7.png",
			"/imgs/zombie/zombie_legs_8.png"
		]
	},
	"Scrawny cat" : {
		walk : {
			top : [
				"/imgs/cat/cat_walk_top_1.png",
				"/imgs/cat/cat_walk_top_2.png",
				"/imgs/cat/cat_walk_top_3.png",
				"/imgs/cat/cat_walk_top_2.png",
				"/imgs/cat/cat_walk_top_1.png"
			],
			down : [
				"/imgs/cat/cat_walk_down_1.png",
				"/imgs/cat/cat_walk_down_2.png",
				"/imgs/cat/cat_walk_down_3.png",
				"/imgs/cat/cat_walk_down_2.png",
				"/imgs/cat/cat_walk_down_1.png"
			],
			left : [
				"/imgs/cat/cat_walk_left_1.png",
				"/imgs/cat/cat_walk_left_2.png",
				"/imgs/cat/cat_walk_left_3.png",
				"/imgs/cat/cat_walk_left_2.png",
				"/imgs/cat/cat_walk_left_1.png"
			],
			right : [
				"/imgs/cat/cat_walk_right_1.png",
				"/imgs/cat/cat_walk_right_2.png",
				"/imgs/cat/cat_walk_right_3.png",
				"/imgs/cat/cat_walk_right_2.png",
				"/imgs/cat/cat_walk_right_1.png"
			]
		},
		wait : {
			top : [
				"/imgs/cat/cat_wait_top_1.png"
			],
			down : [
				"/imgs/cat/cat_wait_down_1.png"
			],
			left : [
				"/imgs/cat/cat_wait_left_1.png"
			],
			right : [
				"/imgs/cat/cat_wait_right_1.png"
			]
		}
	},
	"Scruffy little dog" : {
		walk : {
			top : [
				"/imgs/dog/dog_walk_top_1.png",
				"/imgs/dog/dog_walk_top_2.png",
				"/imgs/dog/dog_walk_top_3.png",
				"/imgs/dog/dog_walk_top_2.png",
				"/imgs/dog/dog_walk_top_1.png"
			],
			down : [
				"/imgs/dog/dog_walk_down_1.png",
				"/imgs/dog/dog_walk_down_2.png",
				"/imgs/dog/dog_walk_down_3.png",
				"/imgs/dog/dog_walk_down_2.png",
				"/imgs/dog/dog_walk_down_1.png"
			],
			left : [
				"/imgs/dog/dog_walk_left_1.png",
				"/imgs/dog/dog_walk_left_2.png",
				"/imgs/dog/dog_walk_left_3.png",
				"/imgs/dog/dog_walk_left_2.png",
				"/imgs/dog/dog_walk_left_1.png"
			],
			right : [
				"/imgs/dog/dog_walk_right_1.png",
				"/imgs/dog/dog_walk_right_2.png",
				"/imgs/dog/dog_walk_right_3.png",
				"/imgs/dog/dog_walk_right_2.png",
				"/imgs/dog/dog_walk_right_1.png"
			]
		}
	},
	explosion : [
		"/imgs/explosion/explosion_1.png",
		"/imgs/explosion/explosion_2.png",
		"/imgs/explosion/explosion_3.png",
		"/imgs/explosion/explosion_4.png",
		"/imgs/explosion/explosion_5.png",
		"/imgs/explosion/explosion_6.png",
		"/imgs/explosion/explosion_7.png",
		"/imgs/explosion/explosion_8.png",
		"/imgs/explosion/explosion_9.png",
		"/imgs/explosion/explosion_10.png",
		"/imgs/explosion/explosion_11.png",
		"/imgs/explosion/explosion_12.png",
		"/imgs/explosion/explosion_13.png",
		"/imgs/explosion/explosion_14.png",
		"/imgs/explosion/explosion_15.png",
		"/imgs/explosion/explosion_16.png",
		"/imgs/explosion/explosion_17.png",
		"/imgs/explosion/explosion_18.png",
		"/imgs/explosion/explosion_19.png",
		"/imgs/explosion/explosion_20.png",
		"/imgs/explosion/explosion_21.png",
		"/imgs/explosion/explosion_22.png",
		"/imgs/explosion/explosion_23.png",
		"/imgs/explosion/explosion_24.png",
		"/imgs/explosion/explosion_25.png",
		"/imgs/explosion/explosion_26.png",
		"/imgs/explosion/explosion_27.png"
	],
    //"Scrawny cat" : "/img/angband/Scrawny cat",
    //"Scruffy little dog" : "/img/angband/Scruffy little dog",
    "Grey mold" : "/imgs/angband/Grey mold.png",
    "Grey mushroom patch" : "/imgs/angband/Grey mushroom patch.png",
    "Giant yellow centipede" : "/imgs/angband/Giant yellow centipede.png",
    "Giant white centipede" : "/imgs/angband/Giant white centipede.png",
    "White icky thing" : "/imgs/angband/White icky thing.png",
    "Large brown snake" : "/imgs/angband/Large brown snake.png",
    "Large white snake" : "/imgs/angband/Large white snake.png",
    "Small kobold" : "/imgs/angband/Small kobold.png",
    "Floating eye" : "/imgs/angband/Floating eye.png",
    "Rock lizard" : "/imgs/angband/Rock lizard.png",
    "Soldier ant" : "/imgs/angband/Soldier ant.png",
    "Fruit bat" : "/imgs/angband/Fruit bat.png",
    "Kobold" : "/imgs/angband/Kobold.png",
    "Metallic green centipede" : "/imgs/angband/Metallic green centipede.png",
    "Yellow mushroom patch" : "/imgs/angband/Yellow mushroom patch.png",
    "White jelly" : "/imgs/angband/White jelly.png",
    "Giant green frog" : "/imgs/angband/Giant green frog.png",
    "Giant black ant" : "/imgs/angband/Giant black ant.png",
    "Salamander" : "/imgs/angband/Salamander.png",
    "Yellow mold" : "/imgs/angband/Yellow mold.png",
    "Metallic red centipede" : "/imgs/angband/Metallic red centipede.png",
    "Cave lizard" : "/imgs/angband/Cave lizard.png",
    "Blue jelly" : "/imgs/angband/Blue jelly.png",
    "Large grey snake" : "/imgs/angband/Large grey snake.png",
    "Raven" : "/imgs/angband/Raven.png",
    "Blue ooze" : "/imgs/angband/Blue ooze.png",
    "Green glutton ghost" : "/imgs/angband/Green glutton ghost.png",
    "Green jelly" : "/imgs/angband/Green jelly.png",
    "Large kobold" : "/imgs/angband/Large kobold.png",
    "Skeleton kobold" : "/imgs/angband/Skeleton kobold.png",
    "Grey icky thing" : "/imgs/angband/Grey icky thing.png",
    "Amulet of Carlammas" : "/imgs/angband/Amulet of Carlammas.png",
    "Amulet of Ingwe" : "/imgs/angband/Amulet of Ingwe.png",
    "Amulet of Elessar" : "/imgs/angband/Amulet of Elessar.png",
    "Ring of Barahir" : "/imgs/angband/Ring of Barahir.png",
    "Ring of Tulkas" : "/imgs/angband/Ring of Tulkas.png",
    "Ring of Narya" : "/imgs/angband/Ring of Narya.png",
    "Ring of Nenya" : "/imgs/angband/Ring of Nenya.png",
    "Ring of Vilya" : "/imgs/angband/Ring of Vilya.png",
    "Full plate armour of Isildur" : "/imgs/angband/Full plate armour of Isildur.png",
    "Mithril plate mail of Celeborn" : "/imgs/angband/Mithril plate mail of Celeborn.png",
    "Leather armour of Himring" : "/imgs/angband/Leather armour of Himring.png",
    "Thalkettoth" : "/imgs/angband/Thalkettoth.png",
    "Shield of Gil-galad" : "/imgs/angband/Shield of Gil-galad.png",
    "Shield of Thorin" : "/imgs/angband/Shield of Thorin.png",
    "Shield of Anárion" : "/imgs/angband/Shield of Anárion.png",
    "Helm of Celebrimbor" : "/imgs/angband/Helm of Celebrimbor.png",
    "Helm of Thranduil" : "/imgs/angband/Helm of Thranduil.png",
    "Crown of Gondor" : "/imgs/angband/Crown of Gondor.png",
    "Crown of NГєmenor" : "/imgs/angband/Crown of Gondor.png",
    "Gloves of Eol" : "/imgs/angband/Gloves of Eol.png",
    "Gloves of Cambeleg" : "/imgs/angband/Gloves of Cambeleg.png",
    "Gloves of Paurnimmen" : "/imgs/angband/Gloves of Paurnimmen.png",
    "Boots of Dal-i-thalion" : "/imgs/angband/Boots of Dal-i-thalion.png",
    "Boots of Thror" : "/imgs/angband/Boots of Thror.png",
    "Boots of Wormtongue" : "/imgs/angband/Boots of Wormtongue.png",
    "Boots of Radagast" : "/imgs/angband/Boots of Radagast.png",
    "Glamdring" : "/imgs/angband/Glamdring.png",
    "Sword of Eowyn" : "/imgs/angband/Sword of Eowyn.png",
    "Orcrist" : "/imgs/angband/Orcrist.png",
    "Anduril" : "/imgs/angband/Anduril.png",
    "Axe of Theoden" : "/imgs/angband/Axe of Theoden.png",
    "Great axe of Durin" : "/imgs/angband/Great axe of Durin.png",
    "Bow of Belthronding" : "/imgs/angband/Bow of Belthronding.png",
    "Bow of Bard" : "/imgs/angband/Bow of Bard.png",
    "Steel arrow" : "/imgs/angband/Steel arrow.png",
    "default_projectile" : "/imgs/default_projectile.png",
    "arrow_projectile" : "/imgs/steel_arrow_projectile.png",
    "fireball_projectile" : "/imgs/default_projectile.png",
})